version: '3.9'

services:
  app:
    build: 
      context: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=todo
      - DB_USER=wilo
      - DB_PASS=0000
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=wilo
      - POSTGRES_PASSWORD=0000
    ports:
      - "5432:5432"

volumes:
  dev-db-data:
